import { useMemo, useState } from "react";
import { BarChart3, Bell, ChevronDown, ClipboardList, Coffee, CreditCard, Database, FileText, Grid2X2, LogOut, Menu, Package, Plus, Receipt, Search, Settings2, ShoppingCart, Store, Users, Wallet, X } from "lucide-react";
import "@/App.css";

const initialProducts = [
  { id: 1, name: "Kopi Susu Gula Aren", category: "Kopi", vendor: "Barista Kopi", price: 18000, cost: 6500, stock: 42, color: "#fff0e6" },
  { id: 2, name: "Americano Ice", category: "Kopi", vendor: "Barista Kopi", price: 15000, cost: 4500, stock: 28, color: "#f6eadf" },
  { id: 3, name: "Nasi Uduk Ayam", category: "Makanan", vendor: "Nasi Uduk Bang Agus", price: 24000, cost: 11500, stock: 18, color: "#fff8dc" },
  { id: 4, name: "Sate Madura 10 Tusuk", category: "Makanan", vendor: "Sate Madura Pak Kumis", price: 30000, cost: 15000, stock: 12, color: "#fee2e2" },
  { id: 5, name: "Croffle Butter", category: "Snack", vendor: "MJD Bakery", price: 16000, cost: 6000, stock: 24, color: "#fff2c6" },
  { id: 6, name: "Matcha Latte", category: "Non-Kopi", vendor: "Barista Kopi", price: 22000, cost: 8000, stock: 9, color: "#e6f4e7" },
];
const money = (n) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(n);
const navItems = [{ id: "overview", label: "Ringkasan", icon: BarChart3 }, { id: "pos", label: "Terminal POS", icon: CreditCard }, { id: "inventory", label: "Inventori & Stok", icon: Package }, { id: "expenses", label: "Pengeluaran", icon: Wallet }, { id: "products", label: "Produk & HPP", icon: ClipboardList }, { id: "reports", label: "Laporan Keuangan", icon: FileText }, { id: "tables", label: "QR Meja", icon: Grid2X2 }];

export default function App() {
  const [role, setRole] = useState("Merchant Admin");
  const [page, setPage] = useState(role === "Kasir" ? "pos" : "overview");
  const [products, setProducts] = useState(() => JSON.parse(localStorage.getItem("mjd-products") || "null") || initialProducts);
  const [cart, setCart] = useState([]);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("Semua");
  const [showReceipt, setShowReceipt] = useState(false);
  const [toast, setToast] = useState("");
  const [sidebar, setSidebar] = useState(false);
  const [expenses, setExpenses] = useState([{ id: 1, category: "Pembelian Bahan Baku", note: "Restock susu & biji kopi", amount: 1250000, date: "12 Jun 2025" }, { id: 2, category: "Listrik & Air", note: "Tagihan bulan berjalan", amount: 850000, date: "10 Jun 2025" }]);
  const filtered = products.filter((p) => (category === "Semua" || p.category === category) && p.name.toLowerCase().includes(query.toLowerCase()));
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.qty, 0);
  const tax = Math.round(subtotal * 0.1); const total = subtotal + tax;
  const notify = (text) => { setToast(text); window.setTimeout(() => setToast(""), 2500); };
  const addToCart = (product) => { setCart((current) => { const found = current.find((item) => item.id === product.id); return found ? current.map((item) => item.id === product.id ? { ...item, qty: item.qty + 1 } : item) : [...current, { ...product, qty: 1 }]; }); };
  const adjustCart = (id, amount) => setCart((current) => current.map((item) => item.id === id ? { ...item, qty: item.qty + amount } : item).filter((item) => item.qty > 0));
  const completeSale = () => { if (!cart.length) return; setShowReceipt(true); setProducts((current) => { const next = current.map((p) => { const line = cart.find((i) => i.id === p.id); return line ? { ...p, stock: p.stock - line.qty } : p; }); localStorage.setItem("mjd-products", JSON.stringify(next)); return next; }); notify("Pesanan berhasil dibayar & tiket vendor dibuat"); };
  const pageTitle = navItems.find((item) => item.id === page)?.label || "Ringkasan";
  return <div className="app-shell" data-testid="mjd-kupi-app">
    <aside className={`sidebar ${sidebar ? "is-open" : ""}`} data-testid="main-sidebar">
      <div className="brand"><div className="brand-mark"><Coffee size={19} /></div><div><strong>MJD Kupi</strong><span>Retail Command Center</span></div><button className="mobile-close" data-testid="close-sidebar-button" onClick={() => setSidebar(false)}><X size={18} /></button></div>
      <div className="workspace-label">WORKSPACE</div><nav>{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={page === id ? "nav-item active" : "nav-item"} data-testid={`nav-${id}`} onClick={() => { setPage(id); setSidebar(false); }}><Icon size={18} /><span>{label}</span>{id === "pos" && <em>Live</em>}</button>)}</nav>
      <div className="sidebar-bottom"><button className="nav-item" data-testid="nav-settings" onClick={() => notify("Pengaturan siap dikonfigurasi") }><Settings2 size={18} /><span>Pengaturan</span></button><div className="sync-card"><div className="sync-icon"><Database size={16} /></div><div><b>Offline-ready</b><span>Data tersimpan lokal</span></div><i /></div><div className="user-card"><div className="avatar">MA</div><div><b>Maya Ardianti</b><span>{role}</span></div><button data-testid="logout-button" onClick={() => notify("Sesi demo tetap aktif")}><LogOut size={16}/></button></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu" data-testid="open-sidebar-button" onClick={() => setSidebar(true)}><Menu size={20}/></button><div className="breadcrumb"><span>MJD Kupi</span><b>/</b><strong>{pageTitle}</strong></div><div className="top-actions"><div className="merchant-switch"><Store size={16}/><span>Outlet Sudirman</span><ChevronDown size={14}/></div><select value={role} onChange={(e) => { setRole(e.target.value); if (e.target.value === "Kasir") setPage("pos"); }} data-testid="role-switcher"><option>Super Admin</option><option>Merchant Admin</option><option>Vendor</option><option>Kasir</option></select><button className="icon-button" data-testid="notifications-button" onClick={() => notify("Tidak ada notifikasi baru")}><Bell size={18}/><i /></button><div className="top-avatar">MA</div></div></header>
      <div className="page-wrap">{page === "overview" && <Overview products={products} expenses={expenses} setPage={setPage} />}{page === "pos" && <POS products={filtered} query={query} setQuery={setQuery} category={category} setCategory={setCategory} cart={cart} addToCart={addToCart} adjustCart={adjustCart} subtotal={subtotal} tax={tax} total={total} completeSale={completeSale} />}{page === "inventory" && <Inventory products={products} setProducts={setProducts} notify={notify} />}{page === "expenses" && <Expenses expenses={expenses} setExpenses={setExpenses} notify={notify} />}{page === "products" && <Products products={products} setProducts={setProducts} notify={notify} />}{page === "reports" && <Reports products={products} expenses={expenses} />}{page === "tables" && <Tables notify={notify} />}</div>
    </main>{toast && <div className="toast" data-testid="toast-message"><span>✓</span>{toast}</div>}{showReceipt && <ReceiptModal total={total} cart={cart} close={() => { setShowReceipt(false); setCart([]); }} />}
  </div>;
}

function SectionHeader({ eyebrow, title, description, action }) { return <div className="section-header"><div><div className="eyebrow">{eyebrow}</div><h1 data-testid="page-heading">{title}</h1><p>{description}</p></div>{action}</div>; }
function Overview({ products, expenses, setPage }) { const stock = products.reduce((a, p) => a + p.stock, 0); return <><SectionHeader eyebrow="SELAMAT PAGI, MAYA" title="Ringkasan operasional" description="Pantau kesehatan Outlet Sudirman dalam satu pandangan." action={<button className="primary-btn" data-testid="overview-pos-button" onClick={() => setPage("pos")}><CreditCard size={16}/> Buka Terminal POS</button>} /><div className="metric-grid"><Metric label="Penjualan hari ini" value="Rp 8.420.000" change="+18,4%" tone="orange" icon={Receipt}/><Metric label="Transaksi selesai" value="126" change="+12 hari ini" tone="green" icon={ShoppingCart}/><Metric label="Laba kotor" value="Rp 3.180.000" change="37,8% margin" tone="blue" icon={BarChart3}/><Metric label="Pengeluaran bulan ini" value={money(expenses.reduce((a, e) => a + e.amount, 0))} change="2 kategori aktif" tone="red" icon={Wallet}/></div><div className="content-grid"><section className="panel chart-panel"><div className="panel-head"><div><h2>Performa penjualan</h2><span>Penjualan bersih · 7 hari terakhir</span></div><button className="date-chip" data-testid="sales-period-button">7 hari <ChevronDown size={14}/></button></div><div className="chart"><div className="chart-y"><span>4jt</span><span>3jt</span><span>2jt</span><span>1jt</span><span>0</span></div><div className="bars">{[54, 72, 48, 86, 66, 92, 78].map((h, i) => <div className="bar-col" key={i}><div className={`bar ${i === 5 ? "selected" : ""}`} style={{ height: `${h}%` }}><b>{i === 5 ? "3,9jt" : ""}</b></div><span>{["Sen", "Sel", "Rab", "Kam", "Jum", "Sab", "Min"][i]}</span></div>)}</div></div></section><section className="panel quick-panel"><div className="panel-head"><div><h2>Aksi cepat</h2><span>Alur kerja yang sering dipakai</span></div></div><QuickAction icon={Plus} title="Tambah produk" detail="Buat menu baru & atur HPP" onClick={() => setPage("products")} /><QuickAction icon={Package} title="Restock inventori" detail={`${stock} unit stok tercatat`} onClick={() => setPage("inventory")} /><QuickAction icon={Wallet} title="Catat pengeluaran" detail="Tambahkan biaya operasional" onClick={() => setPage("expenses")} /></section></div><section className="panel table-panel"><div className="panel-head"><div><h2>Stok menipis</h2><span>Perlu perhatian hari ini</span></div><button className="text-btn" data-testid="inventory-table-link" onClick={() => setPage("inventory")}>Lihat semua <span>→</span></button></div><div className="stock-list">{products.filter(p => p.stock < 20).slice(0, 4).map(p => <div className="stock-row" key={p.id}><div className="product-dot" style={{ background: p.color }}><Coffee size={15}/></div><div className="stock-name"><b>{p.name}</b><span>{p.vendor}</span></div><div className="stock-progress"><div><span style={{ width: `${Math.min(p.stock * 4, 100)}%` }} /></div><small>{p.stock} unit tersisa</small></div><span className="warning-badge">Restock</span></div>)}</div></section></>; }
function Metric({ label, value, change, tone, icon: Icon }) { return <div className="metric" data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}`}><div className={`metric-icon ${tone}`}><Icon size={19}/></div><span>{label}</span><strong>{value}</strong><small className={tone === "red" ? "negative" : "positive"}>{change}</small></div>; }
function QuickAction({ icon: Icon, title, detail, onClick }) { return <button className="quick-action" data-testid={`quick-${title.toLowerCase().replaceAll(" ", "-")}`} onClick={onClick}><div><Icon size={18}/></div><span><b>{title}</b><small>{detail}</small></span><strong>→</strong></button>; }
function POS({ products, query, setQuery, category, setCategory, cart, addToCart, adjustCart, subtotal, tax, total, completeSale }) { return <><SectionHeader eyebrow="TERMINAL KASIR · SHIFT PAGI" title="Pesanan baru" description="Pilih menu, atur jumlah, lalu selesaikan pembayaran." action={<div className="live-pill"><i/> Terminal online</div>} /><div className="pos-layout"><section className="menu-area"><div className="menu-tools"><div className="search-box"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari menu atau scan barcode..." data-testid="pos-product-search" /></div><div className="category-tabs">{["Semua", "Kopi", "Makanan", "Snack", "Non-Kopi"].map(c => <button className={category === c ? "selected" : ""} key={c} onClick={() => setCategory(c)} data-testid={`category-${c.toLowerCase()}`}>{c}</button>)}</div></div><div className="product-grid">{products.map(p => <button className="product-card" key={p.id} onClick={() => addToCart(p)} data-testid={`product-card-${p.id}`}><div className="product-art" style={{ background: p.color }}><Coffee size={30}/><span>{p.stock} stok</span></div><div className="product-info"><b>{p.name}</b><span>{p.vendor}</span><strong>{money(p.price)}</strong></div><div className="add-product"><Plus size={17}/></div></button>)}</div></section><aside className="cart-panel"><div className="cart-head"><div><h2>Keranjang</h2><span data-testid="cart-item-count">{cart.reduce((a, i) => a + i.qty, 0)} item · Meja 07</span></div><button className="clear-btn" onClick={() => cart.forEach(i => adjustCart(i.id, -i.qty))} data-testid="clear-cart-button">Bersihkan</button></div><div className="cart-items">{cart.length ? cart.map(item => <div className="cart-item" key={item.id}><div className="mini-art" style={{ background: item.color }}><Coffee size={16}/></div><div><b>{item.name}</b><span>{money(item.price)}</span><div className="qty"><button onClick={() => adjustCart(item.id, -1)} data-testid={`decrease-${item.id}`}>−</button><strong>{item.qty}</strong><button onClick={() => adjustCart(item.id, 1)} data-testid={`increase-${item.id}`}>+</button></div></div><em>{money(item.price * item.qty)}</em></div>) : <div className="empty-cart"><ShoppingCart size={26}/><b>Keranjang masih kosong</b><span>Pilih menu untuk memulai pesanan</span></div>}</div><div className="cart-summary"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>PPN (10%)</span><b>{money(tax)}</b></div><div className="total-line"><span>Total pembayaran</span><strong>{money(total)}</strong></div><button className="pay-btn" disabled={!cart.length} onClick={completeSale} data-testid="pay-order-button"><CreditCard size={17}/> Bayar sekarang <span>→</span></button><button className="manual-btn" data-testid="manual-order-button"><Plus size={15}/> Tambah item manual</button></div></aside></div></>; }
function Inventory({ products, setProducts, notify }) { const restock = (id) => { const next = products.map(p => p.id === id ? { ...p, stock: p.stock + 10 } : p); setProducts(next); localStorage.setItem("mjd-products", JSON.stringify(next)); notify("Stok berhasil ditambah 10 unit"); }; return <><SectionHeader eyebrow="STOCK ENGINE" title="Inventori & stok" description="Kelola barang masuk, barang keluar, dan audit stok outlet." action={<button className="primary-btn" data-testid="stock-in-button" onClick={() => notify("Form barang masuk siap digunakan")}><Plus size={16}/> Barang masuk</button>} /><div className="metric-grid three"><Metric label="Total unit" value={products.reduce((a, p) => a + p.stock, 0)} change="6 produk aktif" tone="orange" icon={Package}/><Metric label="Stok menipis" value={products.filter(p => p.stock < 15).length} change="Perlu restock" tone="red" icon={Bell}/><Metric label="Nilai persediaan" value="Rp 4,86jt" change="HPP rata-rata" tone="green" icon={BarChart3}/></div><section className="panel table-panel"><div className="panel-head"><div><h2>Ringkasan stok produk</h2><span>Update terakhir: baru saja</span></div><button className="outline-btn" data-testid="stock-opname-button" onClick={() => notify("Mode stock opname dibuka")}>Stock opname</button></div><div className="data-table"><div className="table-row table-label"><span>Produk</span><span>Vendor / Tenant</span><span>HPP unit</span><span>Stok sistem</span><span>Status</span><span /></div>{products.map(p => <div className="table-row" key={p.id}><span className="table-product"><div className="product-dot" style={{ background: p.color }}><Coffee size={14}/></div><b>{p.name}</b></span><span>{p.vendor}</span><span>{money(p.cost)}</span><span><b>{p.stock}</b> unit</span><span><i className={`status-dot ${p.stock < 15 ? "low" : "good"}`} />{p.stock < 15 ? "Menipis" : "Aman"}</span><button className="small-action" onClick={() => restock(p.id)} data-testid={`restock-${p.id}`}><Plus size={14}/> Restock</button></div>)}</div></section></>; }
function Expenses({ expenses, setExpenses, notify }) { const add = () => { setExpenses([...expenses, { id: Date.now(), category: "Lain-Lain", note: "Operasional harian", amount: 275000, date: "Hari ini" }]); notify("Pengeluaran berhasil dicatat"); }; return <><SectionHeader eyebrow="CASH CONTROL" title="Buku pengeluaran" description="Catat dan pantau seluruh biaya operasional outlet." action={<button className="primary-btn" data-testid="add-expense-button" onClick={add}><Plus size={16}/> Catat pengeluaran</button>} /><div className="expense-summary"><div><span>Total bulan ini</span><strong>{money(expenses.reduce((a, e) => a + e.amount, 0))}</strong><small>vs bulan lalu <b>−8,2%</b></small></div><div className="expense-bars"><span style={{ height: "72%" }}/><span style={{ height: "45%" }}/><span style={{ height: "85%" }}/><span style={{ height: "58%" }}/><span style={{ height: "66%" }}/><span style={{ height: "38%" }}/><span style={{ height: "55%" }}/></div></div><section className="panel table-panel"><div className="panel-head"><div><h2>Transaksi pengeluaran</h2><span>Juni 2025 · Outlet Sudirman</span></div><button className="outline-btn" data-testid="expense-filter-button"><Search size={14}/> Filter</button></div><div className="data-table"><div className="table-row table-label"><span>Kategori</span><span>Keterangan</span><span>Tanggal</span><span>Metode</span><span>Nominal</span><span /></div>{expenses.map(e => <div className="table-row" key={e.id}><span><b>{e.category}</b></span><span>{e.note}</span><span>{e.date}</span><span><span className="method-badge">Transfer</span></span><span><b>{money(e.amount)}</b></span><button className="more-btn" data-testid={`expense-menu-${e.id}`}>•••</button></div>)}</div></section></>; }
function Products({ products, setProducts, notify }) { const [name, setName] = useState(""); const save = () => { if (!name) return; const next = [...products, { id: Date.now(), name, category: "Kopi", vendor: "Barista Kopi", price: 20000, cost: 7000, stock: 20, color: "#ffedd5" }]; setProducts(next); localStorage.setItem("mjd-products", JSON.stringify(next)); setName(""); notify("Produk baru berhasil ditambahkan"); }; return <><SectionHeader eyebrow="CATALOG & COSTING" title="Produk & HPP" description="Bangun katalog menu dan jaga margin setiap porsi." action={<button className="primary-btn" data-testid="new-product-button" onClick={() => document.querySelector("#new-product")?.focus()}><Plus size={16}/> Produk baru</button>} /><div className="product-form panel"><div className="form-heading"><div className="form-icon"><ClipboardList size={18}/></div><div><h2>Tambah menu cepat</h2><span>Produk akan masuk ke katalog POS</span></div></div><div className="form-fields"><label>Nama produk<input id="new-product" value={name} onChange={e => setName(e.target.value)} placeholder="Contoh: Es Kopi Pandan" data-testid="product-name-input" /></label><label>Harga jual<input placeholder="Rp 20.000" data-testid="product-price-input" /></label><label>HPP per porsi<input placeholder="Rp 7.000" data-testid="product-cost-input" /></label><button className="primary-btn" onClick={save} data-testid="save-product-button">Simpan produk</button></div></div><div className="catalog-grid">{products.map(p => <div className="catalog-item" key={p.id}><div className="product-art" style={{ background: p.color }}><Coffee size={26}/></div><div><b>{p.name}</b><span>{p.vendor} · {p.category}</span><small>Margin <strong>{Math.round((1 - p.cost / p.price) * 100)}%</strong></small></div><button className="more-btn" data-testid={`product-menu-${p.id}`}>•••</button></div>)}</div></>; }
function Reports({ products, expenses }) { const sales = 8420000, cogs = 3240000, exp = expenses.reduce((a, e) => a + e.amount, 0); return <><SectionHeader eyebrow="FINANCIAL STATEMENT" title="Laporan keuangan" description="Gambaran profitabilitas Outlet Sudirman bulan ini." action={<button className="outline-btn" data-testid="export-report-button" onClick={() => { const blob = new Blob(["MJD Kupi, Laporan Juni\nOmset," + sales], { type: "text/csv" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "mjd-kupi-laporan.csv"; a.click(); }}><FileText size={15}/> Export CSV</button>} /><div className="profit-hero"><div><span>Estimasi laba bersih</span><strong>{money(sales - cogs - exp)}</strong><small><i>↑</i> 14,6% dari bulan lalu</small></div><div className="profit-ring"><div><b>37,8%</b><span>gross margin</span></div></div></div><section className="panel statement"><div className="panel-head"><div><h2>Profit & Loss Statement</h2><span>Periode 01—30 Juni 2025</span></div></div>{[["Penjualan bersih", sales, "income"],["(-) HPP terjual", -cogs, "cost"],["Laba kotor", sales - cogs, "strong"],["(-) Pengeluaran operasional", -exp, "cost"],["Laba bersih", sales - cogs - exp, "total"]].map(([l, v, c]) => <div className={`statement-row ${c}`} key={l}><span>{l}</span><b>{money(v)}</b></div>)}</section></>; }
function Tables({ notify }) { return <><SectionHeader eyebrow="SELF-ORDER STUDIO" title="QR meja pelanggan" description="Buat akses pemesanan unik untuk setiap meja di outlet." action={<button className="primary-btn" data-testid="generate-qr-button" onClick={() => notify("QR meja berhasil dibuat") }><Plus size={16}/> Generate QR</button>} /><div className="table-grid">{Array.from({ length: 12 }, (_, i) => <div className="table-card" key={i}><div className="fake-qr"><span>{String(i + 1).padStart(2, "0")}</span></div><div><b>Meja {i + 1}</b><span>mjdkupi.id/order/{i + 1}</span></div><button className="small-action" data-testid={`print-table-${i + 1}`} onClick={() => notify(`Stiker Meja ${i + 1} siap dicetak`)}>Cetak</button></div>)}</div></>; }
function ReceiptModal({ total, cart, close }) { return <div className="modal-backdrop"><div className="receipt-modal" data-testid="receipt-modal"><button className="modal-close" onClick={close} data-testid="close-receipt-button"><X size={18}/></button><div className="receipt-logo"><Coffee size={17}/></div><h2>MJD Kupi</h2><span>Outlet Sudirman · Struk #MJD-1042</span><div className="receipt-items">{cart.map(i => <div key={i.id}><span>{i.qty}× {i.name}</span><b>{money(i.price * i.qty)}</b></div>)}</div><div className="receipt-total"><span>Total dibayar</span><strong>{money(total)}</strong></div><div className="receipt-status">✓ Pembayaran berhasil</div><button className="primary-btn full" onClick={close} data-testid="finish-receipt-button">Selesai</button></div></div>; }